site_name: AWS Indusrty Blueprints for Data & AI
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Introduction: 'introduction.md'
  - Components definition: 'components.md'
  - Data Ingestion Pipelines: 
    - FHIR Connector: 'comingsoon.md'
    - FiveTran: 'comingsoon.md'
  - Use Case Modules:
    - Database:
      - RDS Plug & Play: 'https://github.com/aws-samples/amazon-isv-plug-n-play'
    - Data Lake:
      - Cabon Data Lake: 'https://aws.amazon.com/solutions/guidance/carbon-data-lake-on-aws/'
      - Data Connector for AWS Data Clean Rooms: 'https://aws.amazon.com/solutions/guidance/connecting-data-clean-rooms/'
    - Data Catalog / Governance:
      - Alation: 'comingsoon.md'
    - Business Insights Accelerators:
      - AWS QuickSignt Gallery: 'https://aws.amazon.com/quicksight/gallery/'
      - CI/CD of QuickSight Assets in SaaS Silo Deployment: 'https://github.com/aws-samples/saas-silo-quicksight-assets-cicd-solution'
      - BI in a Box: 'comingsoon.md'
      - Domo: 'comingsoon.md'
    - Fraud Detection: 'comingsoon.md'
    - ID resolution: 'comingsoon.md'
  - Blueprints:
    - Customer 360: 'comingsoon.md'

markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search